version: '3.8'

services:
  neo4j:
    image: neo4j:5.18.0
    container_name: neo4j_history_graph
    ports:
      - "7474:7474" # HTTP interface
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"] # A useful utility library
    restart: unless-stopped

volumes:
  neo4j_data: